name: arcpy_orchestration

channels:
  - esri
  - conda-forge

dependencies:
  - black>=21
  - openpyxl
  - pip
  - pip:
    - bump2version
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
